name: CI

on:
  push:
      branches: [ main ]
      tags:
        - "v*.*.*"
  pull_request:
      branches: [ main ]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Go
            uses: actions/setup-go@v5
            with:
              go-version: '1.21'
          - name: Install dependencies
            run: go mod download

          - name: Build
            run: ./build.sh

          - name: Run tests
            run: go test -v ./...

          - name: Upload build artifact
            if: github.ref_type == 'tag'
            uses: softprops/action-gh-release@v2
            with:
              files: dist/**