name: CI

on:
  release:
      types: [ created ]
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Go
            uses: actions/setup-go@v5
            with:
              go-version: '1.21'
          - name: Install dependencies
            run: go mod download

          - name: Build
            run: ./build.sh

          - name: Run tests
            run: go test -v ./...
            
    release:
      needs: build-test
      runs-on: ubuntu-latest
      if: github.event_name == 'release'
      steps:
        - name: Upload release artifact
          uses: actions/upload-artifact@v4
          with:
            name: dist
            path: dist